### ISSUE TITLE
gen-mapping is not using latest version of feross/Buffer

### ISSUE THREAD

**Issue by Lookout-ent** [jridgewell/gen-mapping#10]
I'm using Babel/parser and Babel/generator. And i found out Babel is dependent of gen-mapping.
And it seems somewhere gen-mapping or sourcemap-code is not using the latest feross/Buffer , where feross/Buffer is trying to use global which is fixed in the latest version.
I'm not able to figure out how gen-mapping or sourcemap-codec is using Buffer and what version it using.

**Comment by jridgewell** [comment]
`gen-mapping` does't use buffers. `sourcemap-codec` uses [Node's standard buffer implementation](https://nodejs.org/api/buffer.html) as a [fallback](https://github.com/jridgewell/sourcemap-codec/blob/f3d95b857d24fc3f1692dec4d1ed724fe12488a3/src/sourcemap-codec.ts#L24-L30) if `TextDecoder` isn't defined. If `Buffer` isn't defined, we [fallback](https://github.com/jridgewell/sourcemap-codec/blob/f3d95b857d24fc3f1692dec4d1ed724fe12488a3/src/sourcemap-codec.ts#L32-L38) to a slower `String.fromCharCode` implementation.

We don't use `feross/Buffer` anywhere. Only Node's `Buffer`, and even that is optional.
