### ISSUE TITLE
gen-mapping flagged as malware

### ISSUE THREAD

**Issue by ataraxus** [jridgewell/gen-mapping#12]
Hey @jridgewell, our build broke recently because of github is flagging your project as malware. I hope this is a false positive :) 

https://github.com/advisories/GHSA-8rmg-jf7p-4p22

Could you dispute it? 

There are apparently others having the same issue: 

https://github.com/github/advisory-database/issues/3280

Assuming you are not distributing malware on purpose ;)

**Comment by jridgewell** [comment]
`gen-mapping` is not the package that I release. Looks like someone tried to type-squat the official package `@jridgewell/gen-mapping`. I'd trust the GH advisory message, you should treat your systems as compromised.

**Comment by ataraxus** [comment]
Thanks for clarification. Then its grype not correctly parsing the package-lock.json. i have a look on this.

**Comment by ataraxus** [comment]
I could reproduce this with the current version of grype, which apparently gets confused and reported it there (https://github.com/anchore/grype/issues/1886). Sorry for the confusion.
