### ISSUE TITLE
An error will be triggered when using @babel/core@7.7.7

### ISSUE THREAD

**Issue by calmchang** [jridgewell/gen-mapping#15]
In my project, @babel/core@7.7.7 is used to transpile the code. 
Its dependency chain: 【@babel/core@7.7.7 -> @babel/generator@7.26.3 -> @jridgewell/gen-mapping@0.3.5】 is normal. However, an error occurs because @jridgewell/gen-mapping has been upgraded to version 0.3.6：

Error: Cannot find module 'node_modules/@jridgewell/gen-mapping/dist/gen-mapping.umd.js'

**Comment by NoCrypt** [comment]
Please refer to #14

**Comment by easy1090** [comment]
@jridgewell Please set the latest tag to  version 0.3.5 ? Thanks~

**Comment by MuTsunTsai** [comment]
@jridgewell Um, I couldn't find `@jridgewell/gen-mapping` like, at all, on NPM. Did you in fact unpublished the whole thing? I don't think that helps...

**Comment by Zlinni** [comment]
![image](https://github.com/user-attachments/assets/a9b33048-71c3-41b1-925e-4467ffc84eb3)
I'm not sure if published versions can be rolled back, but the latest tag still shows 0.3.6

**Comment by jridgewell** [comment]
v0.3.7 is published now.
