### ISSUE TITLE
find bug

### ISSUE THREAD

**Issue by viastronger** [jridgewell/gen-mapping#16]
last version have a bug, not dist

**Comment by ItsMeKevin1227** [comment]
I have the same issue here.

**Comment by TechPrivacyLab** [comment]
Already fixed: https://github.com/jridgewell/gen-mapping/issues/14#issuecomment-2530760200

**Comment by vrajpal-jhala** [comment]
Duplicate of #14

**Comment by jridgewell** [comment]
v0.3.7 is published now.

**Comment by viastronger** [comment]
> Duplicate of #14

ok,thank you
