### ISSUE TITLE
@jridgewell/gen-mapping error

### ISSUE THREAD

**Issue by chuxin-cs** [jridgewell/gen-mapping#18]
![image](https://github.com/user-attachments/assets/31b0183a-2763-4d7c-9032-2e80cb50fc9b)

@jridgewell/gen-mapping error

**Comment by YiGuaIn** [comment]
什么情况，所有项目都打包不了

**Comment by vrajpal-jhala** [comment]
Maybe duplicate of #14

**Comment by jridgewell** [comment]
v0.3.7 is published now.
