### ISSUE TITLE
0.3.7 version is cached in our private registry and unable to revert back to 0.3.5

### ISSUE THREAD

**Issue by sallams1** [jridgewell/gen-mapping#20]
@jridgewell 
I've been following the debacle of 0.3.6 build issue since the next min it was released to public. 

Builds were failing continuously since 0.3.6 because of missing dist folder and then 0.3.7 was release which was also a disaster due to code issue and then you've reverted the latest tag in npm to 0.3.5 but UNFORTUNATELY, the damage is done and all these versions got copied and cached to our private registry and all our builds are still installing 0.3.7.

Kindly release a new version even if it means releasing 0.3.5 code with 0.3.8 tag so that it will help others who are using private registries

**Comment by rusanz** [comment]
Same problem in our organization, if you can publish 0.3.5 with 0.3.6 tag will be perfect. We have a big problem with pipelines  in CICD with this  library. We need a solution asap.
