### ISSUE TITLE
WEBPACK  Generating SSR bundle failed  Can't import the named export 'put' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by rezavation** [jridgewell/gen-mapping#5]
Hi all,

I've started receiving the following error in my gatsby build, it points to these files:

node_modules/@jridgewell/gen-mapping/node_modules/@jridgewell/trace-mapping/dist/trace-mapping.mjs
node_modules/@jridgewell/gen-mapping/gen-mapping.mjs
node_modules/@jridgewell/trace-mapping/dist/trace-mapping.mjs

```
 ERROR #98123  WEBPACK

Generating SSR bundle failed

Can't import the named export 'put' from non EcmaScript module (only default export is available)

File: ../../node_modules/@jridgewell/gen-mapping/dist/gen-mapping.mjs
```

If I delete these files, my build completes successfully. Can you help me understand whether this package has been incorrectly bundled and deployed, or whether i'm missing something in my gatsby configuration to process this?

My gatsby-node.js has the following:

```
exports.onCreateWebpackConfig = ({ stage, loaders, actions, getConfig }) => {
  if (stage === 'build-javascript' || stage === 'develop') {
    const config = getConfig();
    config.node = {
      fs: 'empty'
    };
    config.resolve.extensions = ['.mjs', '.tsx', '.ts', '.js', '.jsx', '.json'];
    config.module.rules = [
      ...config.module.rules,
      {
        test: /\.mjs$/,
        include: /node_modules/,
        type: 'javascript/auto'
      }
    ];
  }
};
```

and I'm using  @jridgewell/gen-mapping@0.3.2, and @jridgewell/trace-mapping@0.3.14

Any help would be greatly appreciated.

**Comment by jridgewell** [comment]
> Can you help me understand whether this package has been incorrectly bundled and deployed, or whether i'm missing something in my gatsby configuration to process this?

These appear correct to me:
- https://unpkg.com/browse/@jridgewell/gen-mapping@0.3.2/dist/gen-mapping.mjs
- https://unpkg.com/browse/@jridgewell/set-array@1.1.2/dist/set-array.mjs

I'd suggest posting this to either the webpack or gatsby repos, I don't know how to fix this.

**Comment by rezavation** [comment]
Ok, thanks @jridgewell
