### ISSUE TITLE
import issue with babel

### ISSUE THREAD

**Issue by prasanna-m2pfintech** [jridgewell/gen-mapping#8]
```
Failed to compile.

./node_modules/@jridgewell/gen-mapping/dist/gen-mapping.mjs
Can't import the named export 'SetArray' from non EcmaScript module (only default export is available)
```

Facing this issue while trying to run my react project. Tried with v8, v10, v12, v14 and v20 of node, still this issue persist.

**Comment by jridgewell** [comment]
I'm not sure how to help. `@jridgewell/gen-mapping/dist/gen-mapping.mjs` correctly uses ESM import syntax ([`import { SetArray, put } from '@jridgewell/set-array'`](https://www.npmjs.com/package/@jridgewell/gen-mapping?activeTab=code)), and `@jridgewell/set-array` correctly [maps `import` condition](https://www.npmjs.com/package/@jridgewell/set-array/v/1.1.0?activeTab=code) to [ESM code](https://www.npmjs.com/package/@jridgewell/set-array/v/1.1.0?activeTab=code).

**Comment by prasanna3000** [comment]
when I modify the import statements to something like this inside the node-modules, it started working. 
```
import { SetArray, put } from '../../set-array/dist/set-array.mjs';
import { TraceMap, decodedMappings } from '../../trace-mapping/dist/trace-mapping.mjs';
import { encode, decode } from '../../sourcemap-codec/dist/sourcemap-codec.mjs';

```
I tried with v18 now. same issues encountered. This fix seems to work for all the versions.
@jridgewell

**Comment by jridgewell** [comment]
I don't know what to tell you, this plainly works in Node 16 and 18:

```bash
$ cat index.mjs
import { GenMapping } from "@jridgewell/gen-mapping";

console.log(GenMapping);
$ fnm use 16
Using Node v16.19.1
$ node index.mjs
[class GenMapping]
$ fnm use 18
$ node index.mjs
[class GenMapping]
```

Something in your dev setup is causing this, but there's nothing I can do to fix it.
